// This file is auto-generated by the Supabase CLI
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      transactions: {
        Row: {
          id: string
          type: 'income' | 'expense'
          amount: number
          category: string
          description: string | null
          payment_method: string
          reference: string | null
          transaction_date: string
          society_id: string
          created_by: string
          approved_by: string | null
          created_at: string
          updated_at: string
          receipt_url: string | null
        }
        Insert: {
          id?: string
          type: 'income' | 'expense'
          amount: number
          category: string
          description?: string | null
          payment_method: string
          reference?: string | null
          transaction_date: string
          society_id: string
          created_by: string
          approved_by?: string | null
          created_at?: string
          updated_at?: string
          receipt_url?: string | null
        }
        Update: {
          id?: string
          type?: 'income' | 'expense'
          amount?: number
          category?: string
          description?: string | null
          payment_method?: string
          reference?: string | null
          transaction_date?: string
          society_id?: string
          created_by?: string
          approved_by?: string | null
          created_at?: string
          updated_at?: string
          receipt_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "transactions_society_id_fkey"
            columns: ["society_id"]
            referencedRelation: "societies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_created_by_fkey"
            columns: ["created_by"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_approved_by_fkey"
            columns: ["approved_by"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      profiles: {
        Row: {
          id: string
          full_name: string
          email: string
          phone: string | null
          role: 'super_admin' | 'society_admin' | 'committee_member' | 'resident' | 'guest'
          role_id: string | null
          society_id: string
          unit_number: string | null
          is_owner: boolean
          is_active: boolean
          emergency_contact: string | null
          vehicle_details: string | null
          family_members: string[] | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          full_name: string
          email: string
          phone?: string | null
          role?: 'super_admin' | 'society_admin' | 'committee_member' | 'resident' | 'guest'
          role_id?: string | null
          society_id: string
          unit_number?: string | null
          is_owner?: boolean
          is_active?: boolean
          emergency_contact?: string | null
          vehicle_details?: string | null
          family_members?: string[] | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          email?: string
          phone?: string | null
          role?: 'super_admin' | 'society_admin' | 'committee_member' | 'resident' | 'guest'
          role_id?: string | null
          society_id?: string
          unit_number?: string | null
          is_owner?: boolean
          is_active?: boolean
          emergency_contact?: string | null
          vehicle_details?: string | null
          family_members?: string[] | null
          created_at?: string
          updated_at?: string
        }
      }
      society_roles: {
        Row: {
          id: string
          name: string
          description: string | null
          is_default: boolean
          permissions: Json | null
          society_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          is_default?: boolean
          permissions?: Json | null
          society_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          is_default?: boolean
          permissions?: Json | null
          society_id?: string
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}
