// This file is auto-generated by the Supabase CLI
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string
          email: string
          phone: string | null
          role: 'super_admin' | 'society_admin' | 'committee_member' | 'resident' | 'guest'
          role_id: string | null
          society_id: string
          unit_number: string | null
          is_owner: boolean
          is_active: boolean
          emergency_contact: string | null
          vehicle_details: string | null
          family_members: string[] | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          full_name: string
          email: string
          phone?: string | null
          role?: 'super_admin' | 'society_admin' | 'committee_member' | 'resident' | 'guest'
          role_id?: string | null
          society_id: string
          unit_number?: string | null
          is_owner?: boolean
          is_active?: boolean
          emergency_contact?: string | null
          vehicle_details?: string | null
          family_members?: string[] | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          email?: string
          phone?: string | null
          role?: 'super_admin' | 'society_admin' | 'committee_member' | 'resident' | 'guest'
          role_id?: string | null
          society_id?: string
          unit_number?: string | null
          is_owner?: boolean
          is_active?: boolean
          emergency_contact?: string | null
          vehicle_details?: string | null
          family_members?: string[] | null
          created_at?: string
          updated_at?: string
        }
      }
      society_roles: {
        Row: {
          id: string
          name: string
          description: string | null
          is_default: boolean
          permissions: Json | null
          society_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          is_default?: boolean
          permissions?: Json | null
          society_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          is_default?: boolean
          permissions?: Json | null
          society_id?: string
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}
