// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plbaeghsrdfmkvxthbgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYmFlZ2hzcmRmbWt2eHRoYmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNjQzNzAsImV4cCI6MjA3MTY0MDM3MH0.0_UZxnmZokMBbw7zl0jdNHDxuA1rpJk5yRjA-StzO5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});